--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/baba/.local/share/wallpapers/12 - HxlCMmK.jpg"

-- Special
background="#1d2021"
foreground="#eddfd8"
cursor="#afb3a0"

-- Colors
color0="#1d2021"
color1="#363e3d"
color2="#505b56"
color3="#6b796b"
color4="#8c9685"
color5="#afb3a0"
color6="#d0cbbc"
color7="#eddfd8"
color8="#92a1a8"
color9="#7581a9"
color10="#aa9996"
color11="#aa8c57"
color12="#aa6a8a"
color13="#ab3b6c"
color14="#bba930"
color15="#c6bab4"
